package com.ansi.scilla.web.options.response;

public enum ResponseOption {
	INVOICE_GROUPING,
	INVOICE_STYLE,
	INVOICE_TERM,
	JOB_FREQUENCY,
	JOB_STATUS,
	TICKET_STATUS,
	COUNTRY,
	PAYMENT_METHOD,
	PERMISSION,
	REPORT_TYPE,
	WORK_HOURS_TYPE,
	EXPENSE_TYPE,
	CALENDAR_TYPE,
	LOCALE_TYPE,
	DOCUMENT_TYPE,
	JOBTAG_TYPE,
	JOBTAG_STATUS,
	;
}
