package com.ansi.scilla.web.options.response;

public enum ResponseOption {
	INVOICE_GROUPING,
	INVOICE_STYLE,
	INVOICE_TERM,
	JOB_FREQUENCY,
	JOB_STATUS,
	TICKET_STATUS,
	COUNTRY,
	PAYMENT_METHOD,
	PERMISSION,
	ACCOUNT_TYPE,
	REPORT_TYPE,
	WORK_HOURS_TYPE,
	;
}
